name: Build Minimal Arch Tarball

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username for the system"
        required: true
      password:
        description: "Password for the user"
        required: true
      shell:
        description: "Shell path for the user (use /usr/bin/zsh if you have zsh installed)"
        required: true
        default: "/usr/bin/bash"
      timezone:
        description: "Timezone for the system (e.g., America/New_York)"
        required: true
        default: "America/New_York"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create rootfs directory and Build Arch Linux Installation
        run: |
          docker run --privileged --rm -v "$(pwd)":/workspace -v /mnt:/mnt archlinux:latest bash -c '
            set -e
            pacman -Sy --noconfirm arch-install-scripts

            mkdir -p /mnt/arch-root
            pacstrap /mnt/arch-root base linux linux-firmware git curl nano ukify btrfs-progs \
              intel-ucode amd-ucode podman toolbox networkmanager openssh sudo zsh dosfstools

            cp /workspace/rootfs/pacman.conf /mnt/arch-root/etc/pacman.conf
            cp /workspace/rootfs/mirrorlist /mnt/arch-root/etc/pacman.d/mirrorlist

            ln -sf /usr/share/zoneinfo/${{ github.event.inputs.timezone }} /mnt/arch-root/etc/localtime
            echo "${{ github.event.inputs.timezone }}" > /mnt/arch-root/etc/timezone

            useradd -m -G wheel -s ${{ github.event.inputs.shell }} ${{ github.event.inputs.username }}
            echo "${{ github.event.inputs.username }}:${{ github.event.inputs.password }}" | chroot /mnt/arch-root chpasswd

            tar --zstd --numeric-owner --xattrs --acls -C /mnt/arch-root -cf /workspace/arch-custom-rootfs.tar.zst \
              --exclude=./.dockerenv \
              --exclude=./.dockerinit \
              --exclude=./sys/* \
              --exclude=./proc/* \
              --exclude=./dev/* \
              --exclude=./etc/machine-id \
              --exclude=./etc/resolv.conf \
              --exclude=./etc/pacman.d/gnupg/openpgp-revocs.d/* \
              --exclude=./etc/pacman.d/gnupg/private-keys-v1.d/* \
              --exclude=./etc/pacman.d/gnupg/pubring.gpg~ \
              --exclude=./etc/pacman.d/gnupg/S.* \
              --exclude=./root/* \
              --exclude=./tmp/* \
              --exclude=./var/cache/pacman/pkg/* \
              --exclude=./var/lib/pacman/sync/* \
              --exclude=./var/tmp/* \
              .
          '

      - name: Upload Arch Installation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: arch-installation
          path: arch-custom-rootfs.tar.zst
